development:
  adapter: postgresql
  database: sixth_evaluation_development
  username: dev
  password: dev

test:
  adapter: postgresql
  database: sixth_evaluation_test
  username: dev
  password: dev
